#!/bin/sh
# Generated by .github/workflows/build-cuda.yml -- do not edit by hand.
#
# A fallback launcher. You should not need it: qwen38's RUNPATH is $ORIGIN/lib,
# so the plain ./qwen38 finds the bundled runtime by itself.
#
# Reach for this only when the binary is no longer next to its lib/ directory,
# which is what happens if you copy qwen38 somewhere on its own. Then $ORIGIN no
# longer points at the bundle, and this script puts it back on the loader path.
# It also exports CUDA_HOME, which is what Colibri's own CUDA_HOME lookup reads.
#
# Set COLIBRI_BUNDLED_RUNTIME=0 to use a system CUDA install instead.
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

if [ "${COLIBRI_BUNDLED_RUNTIME:-1}" = "1" ] && [ -d "$here/lib" ]; then
    # Appended, not overwritten, so an existing LD_LIBRARY_PATH keeps working
    # and the bundle is only consulted when the system has no libcudart.
    LD_LIBRARY_PATH="$here/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    export LD_LIBRARY_PATH
    CUDA_HOME="${CUDA_HOME:-$here}"
    export CUDA_HOME
fi

exec "$here/BINARY_NAME" "$@"