#!/bin/sh
# Generated by .github/workflows/build-cuda.yml -- do not edit by hand.
#
# qwen38 and coli link libcudart.so.12 and carry RUNPATH
# /usr/local/cuda/lib64, which only exists on a machine with the CUDA toolkit
# installed. The tarball ships the runtime in ./lib, and RUNPATH cannot hold a
# relative path, so this wrapper puts ./lib on LD_LIBRARY_PATH before exec'ing
# the real binary.
#
# Set COLIBRI_BUNDLED_RUNTIME=0 to force use of a system CUDA install instead.
here=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

if [ "${COLIBRI_BUNDLED_RUNTIME:-1}" = "1" ] && [ -d "$here/lib" ]; then
    LD_LIBRARY_PATH="$here/lib${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}"
    export LD_LIBRARY_PATH
    CUDA_HOME="${CUDA_HOME:-$here}"
    export CUDA_HOME
fi

exec "$here/BINARY_NAME" "$@"
